apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerpodautoscaler
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - k8s.practo.dev
  resources:
  - workerpodautoscalers
  - workerpodautoscalers/status
  verbs:
  - list
  - update
  - get
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - update
